### ISSUE TITLE
Getting nil when SubOnce between time.sleep

### ISSUE THREAD

**Issue by cedricve** [cskr/pubsub#17]
I'm running a go routine which is continiously publishing structs. On the other hand I have a go routine which is SubOnce every couple of seconds. What I notice is that when I add a sleep, the subonce start to returning nil values.

Any ideas why?

       for {
		rgb := getImage(ps, dec) // in this function I do the SubOnce
		..
		matArray[2] = &rgb // this rgb is nil
		.. 
		time.Sleep(10 * time.Second)
	}

**Comment by cskr** [comment]
Can you share the contents of `getImage` or a similar code that reproduces the issue?

**Comment by cskr** [comment]
Closing this as there is been no response in a long time. Please reopen with the code to reproduce, if you're still facing the issue.
