### ISSUE TITLE
Unsub can cause deadlock

### ISSUE THREAD

**Issue by nickdavies** [cskr/pubsub#6]
Hey,

I have encountered a deadlock with the library.

Basically when a goroutine that was previously subbed stops listening (in our case when a client disconnects) and calls a defered function to unsub all. But between the time that it stops reading the channel and when it calls unsub something publish's to a channel its subscribed to (this has to publish more messages than the pubsub chan size).

The steps would be (where A and B are different goroutines and R is the registry goroutine):

```
A: x := ps.sub("1") // Which successfully registers
B: ps.pub("testing", "1") // This writes down registry's cmd chan
B: ps.pub("testing", "1") // This writes down registry's cmd chan - assuming buffer of 1
A: unsub(x, "1") // or unsub(x) - which writes unsub down cmd chan
R: reads the pub event
R: send("1", x) // which blocks on ch <- msg
B: ps.pub("testing1", "1") // next event to route
```

And we are all asleep:
A: waits for the registry to read its unsub op
B: waits for the registry to accept its pub op
R: waits for A to accept its pub.

**Comment by nvartolomei** [comment]
Please keep this issue open, so people that want to use this package are aware of existing issues.

**Comment by nvartolomei** [comment]
What about using 2 different command channels for messages and control?
And drain the channel in remove before closing it.
